global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # News Search Microservice metrics
  - job_name: 'news-search-microservice'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['news-search-microservice:8080']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Spring Boot Actuator metrics
  - job_name: 'spring-actuator'
    metrics_path: '/api/v1/actuator/metrics'
    static_configs:
      - targets: ['news-search-microservice:8080']
    scrape_interval: 30s

  # Node Exporter (if running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Redis metrics (if running)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Nginx metrics (if running)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
